# Generated by cucumber-sinatra. (2014-10-03 11:23:57 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rsp.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RSP

class RSPWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RSPWorld.new
end
